### ISSUE TITLE
[Bug Report] Auto-Sizing not always shrinking to fit, on alternate output.

### ISSUE THREAD

**Issue by yurividal** [ChurchApps/FreeShow#910]
I have a secondary NDI output, which I plan to use as OBS lower third.
I have it set to auto-size the text and shrink to fit.

It works in most slides, but doesn't in some. 
See video bellow:
Slide 15 works fine
Slide 16 the text is not resized properly
Slide 21, which has a much biger text, works fine
Slide 20 the text is not resized properly.

https://github.com/user-attachments/assets/c7e7ed56-89d6-426e-8dc0-f020274488ba

**Comment by vassbo** [comment]
Should be fixed here: https://github.com/ChurchApps/FreeShow/releases/tag/v1.3.0-beta.2

**Comment by yurividal** [comment]
@vassbo i think the fix introduced a new bug. Chek out the Scripture refference on top of the verse. It works fine on the preview, and on the first slide, but when i change to the next verse, it goes tiny.
I have already tried to rebuild the template from scratch, it still happens. 

https://github.com/user-attachments/assets/083ae130-f42d-433a-b5ad-6eca23d5fa3c

**Comment by vassbo** [comment]
@yurividal I'm unable to recreate this issue, even with the exact same setup (your template)..

**Comment by yurividal** [comment]
Yeah, I deleted the template a few days ago, and recreated it. It seems to have sorted. Sorry, forgot to mention it here.
Maybe the old template had some residual css that was stuck, I don't know...
Seems fine now, thanks!!!!!!
